invest_house/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home, Sign_up, mypage,exit, setting_login

from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'accounts/lgoun/$', setting_login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/home'}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^$', Home),
    url(r'^home/$', Home, name='home'),
    url(r'^sign-up/$', Sign_up.as_view(), name='sign-up'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^exit-exit_exit/$', exit, name='exit'),

    url(r'^stock/', include('stock.urls', namespace='stock')),

    url(r'^stock_analsis/', include('stock_analysis.urls', namespace="stock_analysis")),

    url(r'^tutorial/', include('tutorial.urls', namespace="tutorial")),

    url(r'^contest/', include('contest.urls', namespace='contest')),

    url(r'^term/', include('term.urls', namespace='term')),
]

term/urls.py
from django.conf.urls import url

from .views import term

urlpatterns = [
    url(r'^$', term, name='term')
]

tutorial/urls.py
from django.conf.urls import url

from .views import tutorial_1,tutorial_2,tutorial_3,tutorial_4,tutorial_5,tutorial_6,tutorial_7,tutorial_8,tutorial_9,tutorial_10

urlpatterns = [
    url(r'^1/$', tutorial_1, name='1'),
    url(r'^2/$', tutorial_2, name='2'),
    url(r'^3/(?P<stock>.+)/$', tutorial_3, name='3'),
    url(r'^4/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_4, name='4'),
    url(r'^5/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_5, name='5'),
    url(r'^6/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_6, name='6'),
    url(r'^7/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_7, name='7'),
    url(r'^8/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_8, name='8'),
    url(r'^9/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_9, name='9'),
    url(r'^10/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_10, name='10'),
]

tutorial/models.py
from django.db import models

# Create your models here.

tutorial/views.py
from django.shortcuts import render

# Create your views here.
def tutorial_1(request):
    return render(request, 'tutorial/tutorial_1.html')

def tutorial_2(request):
    return render(request, 'tutorial/tutorial_2.html')

def tutorial_3(request, stock):
    context = {
        'stock':stock,
    }
    return render(request, 'tutorial/tutorial_3.html', context)

def tutorial_4(request, stock, price1):
    context = {
        'stock':stock,
        'price1':price1,
    }
    return render(request, 'tutorial/tutorial_4.html', context)

def tutorial_5(request, stock, price1):
    context = {
        'stock':stock,
        'price1':price1,
    }
    return render(request, 'tutorial/tutorial_5.html', context)

def tutorial_6(request, stock, price1):
    context = {
        'stock':stock,
        'price1':price1,
    }
    return render(request, 'tutorial/tutorial_6.html', context)

def tutorial_7(request, stock, price1):
    context = {
        'stock':stock,
        'price1':price1,
    }
    return render(request, 'tutorial/tutorial_7.html', context)

def tutorial_8(request, stock, price1, price2):
    context = {
        'stock':stock,
        'price1':price1,
        'price2':price2,
    }
    return render(request, 'tutorial/tutorial_8.html', context)

def tutorial_9(request, stock, price1, price2):
    result = int(price2)-int(price1)
    context = {
        'price1':price1,
        'stock':stock,
        'price2':price2,
        'result':result
    }
    return render(request, 'tutorial/tutorial_9.html', context)

def tutorial_10(request, stock, price1, price2):
    context = {
        'price1':price1,
        'stock':stock,
        'price2':price2,
    }
    return render(request, 'tutorial/tutorial_10.html', context)

templates/tutorial/tutorial_1.html
<!DOCTYPE html>
<html>
<head>
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 200px;
    width: 200px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
    a{
        color: #000;
    }
</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static 'flthtmqnsflwha.png' %}" style="height:500px; width:600px">
  <div id="absolute1">
    <div>{{ request.user.nickname }}님</div>
    <div>환영합니다</div>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:2' %}">></a>
  </div>

</body>
</html>

templates/tutorial/tutorial_10.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 10px;
        left: 480px;
    width: 200px;
    height: 100px;
}
    div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        padding: 10px
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-top: 140px;
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">이제 또 다른 주식들을 사고팔면서<br> 돈을 벌어보세요!</div>
  </div>
</div>


<div id="absolute3">
    <a href="{% url 'tutorial:9' stock price1 price2 %}"><</a>
  </div>



</body></html>

templates/tutorial/tutorial_2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 40px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {

    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        margin-top: 10px;
        padding: 10px;
        width: 300px;
        font-size: 25px;
        border: none;
        color: #fff;
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div>다음 중 원하는 주식을 선택해보세요</div>
    <div><button  value="농촌치킨" class="btn" onclick="change(this.value)" >농촌치킨</button></div>
    <div><button value="드러오래" class="btn" onclick="change(this.value)">드러오래</button></div>
    <div><button value="투할머니보쌈" class="btn" onclick="change(this.value)">투할머니보쌈</button></div>
    <div><button  value="가나피자" class="btn" onclick="change(this.value)">가나피자</button></div>
    <div><button  value="맛나피자" class="btn" onclick="change(this.value)">맛나피자</button></div>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:3' '농촌치킨' %}">></a>
  </div>
    <div id="absolute3">
    <a href="{% url 'tutorial:1' %}"><</a>
  </div>
  <script type="text/javascript">
    function change(val){
      document.getElementById("absolute2").getElementsByTagName("a")[0].setAttribute("href", "/tutorial/3/"+val+"/")
    }
  </script>
</body>
</html>

templates/tutorial/tutorial_3.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        margin-top: 10px;
        padding: 10px;
        width: 80px;
        border: none;
        color: #fff;
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">원하는 가격을 선택해주세요</div>
        <div style="
    text-align: left;
    color: blue;
">{{ stock }}</div>
    <table>
      <tbody><tr>
        <td style="
    padding-right: 10px;">
  {% load static %}
<img src="{% static 'tutorialchart.png' %}" style="
    width: 370px;
    height: 300px;
">
</td>
<td>
<div><button value="100000" class="btn" onclick="change(this.value)">100000</button></div>
<div><button value="120000" class="btn" onclick="change(this.value)">120000</button></div>
<div><button value="150000" class="btn" onclick="change(this.value)">150000</button></div>
</td>
  </tr>
</tbody></table>

</div>
</div>

<div id="absolute2">
<a href="{% url 'tutorial:4' stock '100000' %}">&gt;</a>
</div>

<div id="absolute3">
<a href="{% url 'tutorial:2' %}"><</a>
</div>

<script type="text/javascript">
function change(val){
document.getElementById("absolute2").getElementsByTagName("a")[0].setAttribute("href", "/tutorial/4/{{ stock }}/"+val+"/")
}
</script>
</body></html>

templates/tutorial/tutorial_4.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        margin-top: 10px;
        padding: 10px;
        width: 300px;
        font-size: 25px;
        border: none;
        color: #fff;
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">매수신청을 해보세요</div>
      <div style="
    margin-top: 130px;
    font-size: 50px;
">
        <span style="
    margin: 30px;
">매도</span>
        <span style="
    margin: 30px;
"><button class="btn">매수</button></span>
      </div>
      <p style="margin-top: 90px; color: gray;text-align: right;">선택한 가격으로 매수 신청을 할 수 있습니다.<br>선택한 가격과 주가가 같아지면 체결이 되어 주식을 소유하게됩니다.</p>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:5' stock price1 %}">&gt;</a>
  </div>

<div id="absolute3">
    <a href="{% url 'tutorial:3' stock %}"><</a>
  </div>


</body></html>

templates/tutorial/tutorial_5.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 180px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        padding: 10px
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">1주일 뒤...</div>


  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:6' stock price1 %}">&gt;</a>
  </div>

<div id="absolute3">
    <a href="{% url 'tutorial:4' stock price1 %}"><</a>
  </div>


</body></html>

templates/tutorial/tutorial_6.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
    div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        padding: 10px
    }
    td{
        padding: 10px
    }
</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">주식이 올랐어요! 축하드려요</div>
      <div style="
    font-size: 50px;
    margin-left: 40px;
">
        <table style="
    text-align: center;
    width: 400px;
    font-size: x-large;
">
          <tbody><tr style="
    background-color: gainsboro;
">
            <td>종목명</td>
            <td>현재가</td>
            <td style="width: 110px;">↑/↓</td>
            </tr>
            <tr>
            <td>농촌치킨</td>
            <td>200000</td>
            <td>+2.3%</td>
            </tr>
            <tr>
            <td>드러오래</td>
            <td>160000</td>
            <td>+1.23%</td>
            </tr>
            <tr>
            <td>투할머니보쌈</td>
            <td>190000</td>
            <td>+1.5%</td>
            </tr>
            <tr>
            <td>가나피자</td>
            <td>180000</td>
            <td>+0.57</td>
            </tr>
            <tr>
            <td>맛나피자</td>
            <td>175000</td>
            <td>+0.42</td>
            </tr>
          </tbody></table>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:7' stock price1 %}">&gt;</a>
  </div>

<div id="absolute3">
    <a href="{% url 'tutorial:5' stock price1 %}"><</a>
  </div>


</div></body></html>

templates/tutorial/tutorial_7.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 20px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        padding: 10px
    }
     .btn{
        margin-top: 10px;
        padding: 10px;
        width: 80px;
        border: none;
        color: #fff;
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
"><div>이제 원하는 주식을 팔아볼게요</div><div style="
    margin-top: 10px;
    font-size: 20px;
">원하는 가격을 선택해주세요</div></div>
        <div style="
    text-align: left;
    color: blue;
">{{ stock }}</div>
    <table>
      <tbody><tr>
        <td style="
    padding-right: 10px;
">      <img src="{% static 'tutorialchart2.png' %}" style="
    width: 370px;
    height: 300px;
">
</td>
      <td><div><button value="170000" class="btn" onclick="change(this.value)">170000</button></div>
      <div><button value="180000" class="btn" onclick="change(this.value)">180000</button></div>
      <div><button value="200000" class="btn" onclick="change(this.value)">200000</button></div>
          </td>
        </tr>
      </tbody></table>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:8' stock price1  '170000' %}">&gt;</a>
  </div>
<div id="absolute3">
    <a href="{% url 'tutorial:6' stock  price1 %}"><</a>
  </div>

  <script type="text/javascript">
  function change(val){
  document.getElementById("absolute2").getElementsByTagName("a")[0].setAttribute("href", "/tutorial/8/{{ stock }}/{{ price1 }}/"+val+"/")
  }
  </script>

</body></html>

templates/tutorial/tutorial_8.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        margin-top: 10px;
        padding: 10px;
        width: 130px;
        border: none;
        color: #fff;
        font-size: 50px
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">매도신청을 해보세요</div>
      <div style="
    margin-top: 130px;
    font-size: 50px;
">
        <span style="
    margin: 30px;
"><button class="btn">매도</button></span>
        <span style="
    margin: 30px;
">매수</span>
      </div>
      <p style="
    margin-top: 130px;
    color: gray;
    text-align: right;
">매도 버튼을 클릭하시면 다음 단계로 넘어갑니다</p>
  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:9' stock  price1  price2 %}">&gt;</a>
  </div>

<div id="absolute3">
    <a href="{% url 'tutorial:7' stock price1 %}"><</a>
  </div>


</body></html>

templates/tutorial/tutorial_9.html
<html><head>
    <meta charset="utf-8">
<style>
div.relative {
    position: relative;
    width: 600px;
    height: 500px;
}

div#absolute1 {
    text-align: center;
    position: absolute;
    top: 30px;
    left: 50px;
    width: 500px;
    height: 100px;
}
    div#absolute2 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
        left: 480px;
    width: 200px;
    height: 100px;
}
     div#absolute3 {
    font-size: 30px;
    text-align: center;
    position: absolute;
    top: 180px;
    left: 20px;
    height: 100px;
}
    a{
        color: #000;
    }
    .btn{
        margin-top: 10px;
        padding: 10px;
        width: 130px;
        border: none;
        color: #fff;
        font-size: 50px
    }

</style>
</head>
<body>


<div class="relative">
  {% load static %}
  <img src="{% static '2.png' %}" style="height:500px; width:600px">

  <div id="absolute1">
    <div style="
    margin-bottom: 30px;
    font-size: 30px;
    font-weight: 600;
">체결되었습니다-!</div>
      <div style="
    margin-top: 130px;
    font-size: 50px;
">
        내 통장잔고 :<span style="
    color: #DD4329;
">{{ result }}원</span>
      </div>

  </div>
</div>

  <div id="absolute2">
    <a href="{% url 'tutorial:10' stock price1  price2 %}">&gt;</a>
  </div>
<div id="absolute3">
    <a href="{% url 'tutorial:8' stock price1 price2 %}"><</a>
  </div>



</body></html>