contest/urls.py
from django.conf.urls import url

from .views import contest

urlpatterns=  [
    url(r'^$', contest, name='contest'),
]

invest_house/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home, Sign_up, mypage,exit, setting_login

from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'accounts/lgoun/$', setting_login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/home'}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^$', Home),
    url(r'^home/$', Home, name='home'),
    url(r'^sign-up/$', Sign_up.as_view(), name='sign-up'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^exit-exit_exit/$', exit, name='exit'),

    url(r'^stock/', include('stock.urls', namespace='stock')),

    url(r'^stock_analsis/', include('stock_analysis.urls', namespace="stock_analysis")),

    url(r'^tutorial/', include('tutorial.urls', namespace="tutorial")),

    url(r'^contest/', include('contest.urls', namespace='contest')),

    url(r'^term/', include('term.urls', namespace='term')),
]

stock/urls.py
from django.conf.urls import url

from .views import main, stock_detail, stock_search, balances, stock_request, ranking, random_stock, buy_sell


urlpatterns = [
    url(r'^main/$', main, name='main'),
    url(r'random_stock/$', random_stock, name='random_stock'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/$', stock_detail, name='stock_detail'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/buy_sell/$', buy_sell, name='buy_sell'),
    url(r'^search/$', stock_search, name='search'),
    url(r'^request/(?P<code>[A-Za-z-0-9]+)/$', stock_request, name="request"),
    url(r'^balances/$', balances, name="Balances"),
    url(r'^ranking/$', ranking, name="ranking"),
]

stock_analysis/urls.py
from django.conf.urls import url

from .views import trade, increase, decrease

urlpatterns = [
    url(r'^$', trade, name='first'),
    url(r'^trade/$', trade, name="trade"),
    url(r'^increase/$', increase, name='increase'),
    url(r'^decrease/$', decrease, name='decrease'),
]

term/urls.py
from django.conf.urls import url

from .views import term

urlpatterns = [
    url(r'^$', term, name='term')
]

tutorial/urls.py
from django.conf.urls import url

from .views import tutorial_1,tutorial_2,tutorial_3,tutorial_4,tutorial_5,tutorial_6,tutorial_7,tutorial_8,tutorial_9,tutorial_10

urlpatterns = [
    url(r'^1/$', tutorial_1, name='1'),
    url(r'^2/$', tutorial_2, name='2'),
    url(r'^3/(?P<stock>.+)/$', tutorial_3, name='3'),
    url(r'^4/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_4, name='4'),
    url(r'^5/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_5, name='5'),
    url(r'^6/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_6, name='6'),
    url(r'^7/(?P<stock>.+)/(?P<price1>[0-9]+)/$', tutorial_7, name='7'),
    url(r'^8/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_8, name='8'),
    url(r'^9/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_9, name='9'),
    url(r'^10/(?P<stock>.+)/(?P<price1>[0-9]+)/(?P<price2>[0-9]+)/$', tutorial_10, name='10'),
]

templates/Sign_up.html
<!DOCTYPE html>
<!--css가 꼬여서 상속을 안함-->
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <style>
    /*파일 분리할 것*/
    /*전체적용*/
    html {
        background: url({% static 'loginBg.png' %}) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    body {
        margin: 0;
    }
    .main-header {
        font-size: 30px;
        color: #fff;
        text-align: center;
        background-color: #3337D3;
        height: 50px;
        padding-top: 30px;
    }
    a:link { color: black; text-decoration: none;}
    a:visited { color: black; text-decoration: none;}
    a:hover { color: black; text-decoration: underline;}
    nav {
       width: 470px;
       margin: 0 auto
    }
    .container{

    }
    /*이 문서만 적용*/

    .login-card-container{
       position: relative;
    margin-top: 70px;
    margin-right: 70px;
    width: 600px;
    height: 400px;
    text-align: center;
    float: right;
    left: 0;

    }
    .login-card {
        margin-left: 10%;
        margin-right: 10%;
        width: 500px;
    }

    .card-header {
        font-size: 40px;
    }

    .UIInput {
        height: 20px;
        float: left;
    }

    .login-icon {
        width: 15px;
        margin: 0;
    }

    .login-line {
        border-width: 0.5px;
        border-style: solid;
    }
    .UI{
        margin-top: 30px;
    }
    .UIInput-input {
        background-color: rgba(0, 0, 0, 0);
        height: 100%;
        margin-left: 10px;
        border: none;
        width: 450px;
        font-size: 15px;
        line-height: 10%;
    }

    *:focus {
        outline: none;
    }
    #movetoM{
        float: right;
        font-size: 15px;
    }
    .login-btn {
        margin-top: 70px;
        font-size: 20px;
        color: #fff;
        background-color: #CECECE;
        width: 100%;
        border: none;
        padding: 10px;
    }
</style>
  </head>
  <body>
    <div style="height: 120px;padding-bottom: 1px;background-color: #333FD3;color: #fff;padding-top: 10px;padding-left: 10px;padding-right: 10px;">
      {% if request.user.is_authenticated %}
      <div style="float: right;"> <span style="padding-right: 5px;">{{ request.user.nickname }}</span>
        <span style="padding-left: 10px;border-left-style: solid;border-width: 1px;"><a href="{% url 'logout' %}"style="color:white;">로그아웃</a></span>
      </div>
      {% endif %}
      <div style="position: relative;text-align: center;font-size: 60px;margin-top: 20px;">
        <a href="{% url 'stock:main' %}"><img src="{% static 'logo.png' %}" style="top: -8px;bottom: 0px;position: absolute;height: 100px;width: 215px;E/* left: 1px; */"></a>
      Blue chip </div>
      {% if request.user.is_authenticated %}
      <form action="{% url 'stock:search' %}" method="POST" style="margin: 0px;float: right;">
        {% csrf_token %}
          <input id='id_title' name='title'type="text" class="form-control" placeholder="검색" style="border-width: 1px;/* border: 1px; */width: 200px;background-color: #333FD3;border: none;border-bottom-style: solid;border-color: #fff;">
    </form>
    {% endif %}
  </div>
  {% if request.user.is_authenticated %}
      <nav>
        <b><a href="{% url 'stock:random_stock' %}">주식</a> | <a href="{% url 'stock_analysis:first' %}">주식 분석</a> | <a href="{% url 'stock:Balances' %}">잔고</a> |
         <a href="{% url 'stock:ranking' %}">순위</a> | <a href="{% url 'contest:contest' %}">대회 공지</a> | <a href="{% url 'tutorial:tutorial_1' %}">튜토리얼</a> | <a href="{% url 'term:term' %}">용어 사전</a> <br></b>
      </nav>
  {% endif %}
  <div class="container">
  <!--    로그인 카드-->
      <div class="login-card-container">
                      <img src="{% static 'login600400.png' %}" style="height: 520px;right: 0px;position: absolute;z-index: -1;width: 100%;">

      <div class="login-card">
          <div class="card-header">
              <p>Membership</p>
          </div>
          <div class="card-body">
            <form class="" action="{% url 'sign-up' %}" method="post">
              {% csrf_token %}
              <div class="UI">
                  <div class="UIInput">
                      <img src="{% static 'id.png' %}" class="login-icon">
                      <input name="username" spellcheck="false" autocorrect="off" placeholder="아이디" class="UIInput-input" type="text">
                  </div>
                  <br>
                  <hr class="login-line">
              </div>
              <div class="UI">
                  <div class="UIInput">
                      <img src="{% static 'nickname.png' %}" class="login-icon">
                      <input name="nickname" spellcheck="false" autocorrect="off" placeholder="닉네임" class="UIInput-input" type="text">
                  </div>
                  <br>
                  <hr class="login-line">
              </div>

              <div class="UI">
                  <div class="UIInput">
                      <img src="{% static 'lock.png' %}" class="login-icon">
                      <input name="password1" spellcheck="false" autocorrect="off" placeholder="비밀번호" class="UIInput-input"type="password">
                  </div>
                  <br>
                  <hr class="login-line">
              </div>
              <div class="UI">
                  <div class="UIInput">
                      <img src="{% static 'lock.png' %}" class="login-icon">
                      <input name="password2" spellcheck="false" autocorrect="off" placeholder="비밀번호 확인" class="UIInput-input" type="password">
                  </div>
                  <br>
                  <hr class="login-line">
              </div>
          </div>
          <div class="card-footer">
              <input class="login-btn" type="submit" name="name" value="회원가입" />
          </div>
        </form>
      </div>
    </div>
  </div>
  </body>
  <script>
      $(document).ready(function(){
          $("#id_nickname").attr('placeholder', '{{ form.nickname.label }}');
          $("#id_username").attr('placeholder', '{{ form.username.label }}');
          $("#id_password1").attr('placeholder', '{{ form.password1.label }}');
          $("#id_password2").attr('placeholder', '{{ form.password2.label }}');
      });
  </script>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheet %}{% endblock %}
    {% load static %}
    <link href="{% static 'Dashboard Template for Bootstrap_files/bootstrap-combined.min.css' %}" rel="stylesheet" id="bootstrap-css">
    <link href="{% static "Dashboard Template for Bootstrap_files/bootstrap.min.js" %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
        window.alert = function(){};
        var defaultCSS = document.getElementById('bootstrap-css');
        function changeCSS(css){
            if(css) $('head > link').filter(':first').replaceWith('<link rel="stylesheet" href="'+ css +'" type="text/css" />');
            else $('head > link').filter(':first').replaceWith(defaultCSS);
        }
        $( document ).ready(function() {
          var iframe_height = parseInt($('html').height());
          window.parent.postMessage( iframe_height, 'http://bootsnipp.com');
        });
    </script>
    <style media="screen">
      .red {
        color: #d40400;
      }
      .blue {
        color: #005dde;
      }
      .modal {
          display: none; /* Hidden by default */
          position: fixed; /* Stay in place */
          z-index: 1; /* Sit on top */
          padding-top: 100px; /* Location of the box */
          left: 0;
          top: 0;
          width: 100%; /* Full width */
          height: 100%; /* Full height */
          overflow: auto; /* Enable scroll if needed */
          background-color: rgb(0,0,0); /* Fallback color */
          background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
      }
      /* Modal Content */
      .modal-content {
          background-color: #fefefe;
          margin-left: 30%;
          padding: 20px;
          border: 1px solid #888;
          width: 650px;
      }
      /* The Close Button */
      .close {
          color: #aaaaaa;
          float: right;
          font-size: 28px;
          font-weight: bold;
      }
      .close:hover,
      .close:focus {
          color: #000;
          text-decoration: none;
          cursor: pointer;
      }
    </style>
</head>
<body style="background-color:#F8F0ED">
<div id="myModal" class="modal" style="margin-left: 0;display: none;">
  <!-- Modal content -->
  <div class="modal-content"  >
  <span class="close">×</span>
      <div style="box-shadow: none;background: none;border: none;">
          <iframe src="{% url 'tutorial:1' %}" style="border: none;width: 742px;height: 520px;"></iframe>
      </div>
   </div>
</div>

  <div style="height: 120px;padding-bottom: 1px;background-color: #333FD3;color: #fff;padding-top: 10px;padding-left: 10px;padding-right: 10px;">
    <img src="{% static 'headerImage.png' %}" style="position: absolute;width: 150;height: 90px;bottom: 10px;top:30px;left:10px;">
    {% if request.user.is_authenticated %}
    <div style="float: right;"> <span style="padding-right: 5px;"><a href="{% url 'mypage' %}" style="padding: 0;;color: #fff;padding-left: 10px;">{{ request.user.nickname }}님 반갑습니다!</a></span>
      <span style="padding-left: 10px;border-left-style: solid;border-width: 1px;"><a href="{% url 'logout' %}" style="color:white;">로그아웃</a></span>
    </div>
    {% endif %}
    <!--he-->
    <div style="right: 120px; position: relative;text-align: center;font-size: 60px;margin-top: 20px;">
      <a href="{% url 'stock:main' %}"><img src="{% static 'logo.png' %}" style="top: -8px;bottom: 0px;position: absolute;height: 100px;width: 215px;E/* left: 1px; */"></a>
      <span style="position:absolute; top:30px;">Blue Chip</span>
    </div>
    {% if request.user.is_authenticated %}
    <form action="{% url 'stock:search' %}" method="POST" style="margin: 0px;float: right;">
      {% csrf_token %}
      <input id='id_title' name='title' type="text" class="form-control" placeholder="검색" style="color:#fff;margin-top:60px;border-width: 1px;/* border: 1px; */width: 200px;background-color: #333FD3;border: none;border-bottom-style: solid;border-color: #fff;">
  </form>
  {% endif %}
</div>
{% if request.user.is_authenticated %}
<nav style="text-align: center;margin-top: 20px;margin-bottom: 20px;font-size: 20px;">
  <b><a href="/stock/random_stock/" style="color: #000;">주식</a> | <a href="/stock_analsis/" style="color: #000;">주식 분석</a> | <a href="/stock/balances/" style="color: #000;">잔고</a> |
   <a href="/stock/ranking/" style="color: #000;">순위</a> | <a href="/contest/" style="color: #000;">대회 공지</a> | <a id="myBtn" style="color: #000; cursor: pointer;">튜토리얼</a> | <a href="/term/" style="color: #000;">용어 사전</a> <br></b>
</nav>
{% endif %}
    {% block body %}
    {% endblock %}
</body>
{% block javascript %}{% endblock %}
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
if (event.target == modal) {
    modal.style.display = "none";
}
}
</script>
</html>

templates/base2.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheet %}{% endblock %}
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--    <link rel="icon" href="">-->
    <!-- Bootstrap core CSS -->
    <link href="{% static "Dashboard Template for Bootstrap_files/bootstrap.min.css" %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "Dashboard Template for Bootstrap_files/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static "Dashboard Template for Bootstrap_files/dashboard.css" %}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "Dashboard Template for Bootstrap_files/ie-emulation-modes-warning.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style media="screen">
    .red {
      color: #d40400;
    }
    .blue {
      color: #005dde;
    }
/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin-left: 300px;
    padding: 20px;
    border: 1px solid #888;
    width: 650px;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}
    </style>
  </head>
  <body style="background-color:#F8F0ED">
    <div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content" >
    <span class="close">×</span>
        <div style="box-shadow: none;background: none;border: none;">
            <iframe src="{% url 'tutorial:1' %}" style="border: none;width: 742px;height: 520px;"></iframe>
        </div>
    </div>
</div>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="
    background-color: #CECECE;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'stock:main' %}" style="/* padding-bottom: 6px; */"><img src="{% static 'graylogo.png' %}" style="width: 145px;height: 35px;padding-bottom: 12px;/* margin-bottom: 7px; */"></a>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right" style="margin-top: 25px;">
                    <li style="color: #fff;padding-right: 10px;padding-left: 10px;"><a href="{% url 'mypage' %}" style="padding: 0;color: #fff;padding-left: 10px;"><a href="{% url 'mypage' %}" style="padding: 0;;color: #fff;padding-left: 10px;">{{ request.user.nickname }}님 반갑습니다!</a></li>
                    <li style="border-left-style: solid;color: #fff;padding-right: 10px;padding-left: 10px;"><a style="padding: 0;border-left-style: solid;color: #fff;padding-left: 10px;" href="{% url 'logout' %}">로그아웃</a></li>
                </ul>
                <form action="{% url 'stock:search' %}" method="POST" class="navbar-form navbar-right">
                    {% csrf_token %}
                    <input id='id_title' name='title' type="text" class="form-control" style="color : #000" placeholder="검색">
                </form>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    <script src="{% static "Dashboard Template for Bootstrap_files/jquery.min.js" %}"></script>
    <script>
        //window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
    </script>
    <script src="{% static "Dashboard Template for Bootstrap_files/bootstrap.min.js" %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static "Dashboard Template for Bootstrap_files/holder.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "Dashboard Template for Bootstrap_files/ie10-viewport-bug-workaround.js" %}"></script>
    <script>
    // Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
  </body>
</html>

templates/mypage.html
{% extends 'base2.html' %}

{% block title %}마이페이지{% endblock %}

{% block body %}
{% load  static %}
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar" style="padding-top: 0px;background-color: #3338D3;">
    <ul class="nav nav-sidebar">
        <li>
            <a href="{% url 'stock:random_stock' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stockicon.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">종목</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock_analysis:first' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stock2.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">주식분석</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock:Balances' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'leftmoney.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">잔고</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock:ranking' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'rank.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">순위</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'contest:contest' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'competition.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">대회공지</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>

        <li id="myBtn">
            <a href="#" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'tutorial.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">튜토리얼</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'term:term' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static  'dic.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">용어사전</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
    </ul>
    <img src="{% static 'sidebarBg.png' %}"style="position: absolute;height: 150px;right: 0;bottom: 0;">
</div>
    </div>
</div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;">
            <div class="row">
                <div class="col-sm-8 blog-main" style="margin-bottom: 30px;">
                  <div class="blog-post" style="background-color: #fff;">
                      <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">자산</span></h4>
                      <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>아이디</th>
                                <th>닉네임</th>
                                <th>통장잔액</th>
                                <th>보유 주식 가치</th>
                                <th>총자산</th>
                            </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>{{ request.user.username }}</td> <td>{{ request.user.nickname }}</td>
                            <td>{{ request.user.money }}</td> <td>{{ request.user.take_price }}</td> <td>{{ request.user.total_money }}</td>
                          </tr>
                        </tbody>
                        </table>
                  </div>
                  <div>
                    <img src="{% static 'pasan.png' %}" alt="" />
                    <span>파산 신청을 하면 모든 주식이 사라지고 통장잔액이 100000원이 됩니다.</span> <br>
                    <a href="{% url 'exit' %}" style="text-decoration:none; color:black;" ><b>파산 신청!(경고 없이 바로 파산됩니다!)</b></a>
                  </div>
              </div>
           </div>
       </div>
    </div>
</div>

{% endblock %}