contest/urls.py
from django.conf.urls import url

from .views import contest

urlpatterns=  [
    url(r'^$', contest, name='contest'),
]

invest_house/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home, Sign_up, mypage,exit, setting_login

from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'accounts/lgoun/$', setting_login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/home'}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^$', Home),
    url(r'^home/$', Home, name='home'),
    url(r'^sign-up/$', Sign_up.as_view(), name='sign-up'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^exit-exit_exit/$', exit, name='exit'),

    url(r'^stock/', include('stock.urls', namespace='stock')),

    url(r'^stock_analsis/', include('stock_analysis.urls', namespace="stock_analysis")),

    url(r'^tutorial/', include('tutorial.urls', namespace="tutorial")),

    url(r'^contest/', include('contest.urls', namespace='contest')),

    url(r'^term/', include('term.urls', namespace='term')),
]

stock/urls.py
from django.conf.urls import url

from .views import main, stock_detail, stock_search, balances, stock_request, ranking, random_stock, buy_sell


urlpatterns = [
    url(r'^main/$', main, name='main'),
    url(r'random_stock/$', random_stock, name='random_stock'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/$', stock_detail, name='stock_detail'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/buy_sell/$', buy_sell, name='buy_sell'),
    url(r'^search/$', stock_search, name='search'),
    url(r'^request/(?P<code>[A-Za-z-0-9]+)/$', stock_request, name="request"),
    url(r'^balances/$', balances, name="Balances"),
    url(r'^ranking/$', ranking, name="ranking"),
]

stock_analysis/urls.py
from django.conf.urls import url

from .views import trade, increase, decrease

urlpatterns = [
    url(r'^$', trade, name='first'),
    url(r'^trade/$', trade, name="trade"),
    url(r'^increase/$', increase, name='increase'),
    url(r'^decrease/$', decrease, name='decrease'),
]

term/urls.py
from django.conf.urls import url

from .views import term

urlpatterns = [
    url(r'^$', term, name='term')
]

stock/forms.py
from django import forms
from stock.models import Stock

class searchForm(forms.ModelForm):

    class Meta:
        model = Stock
        fields = ['title']
        labels = {
            'title':'종목 이름'
        }

MY_CHOICES = (
    ('0', '매도'),
    ('1', '매수'),
)

class requestForm(forms.Form):
    request_flag = forms.ChoiceField(choices=MY_CHOICES)
    request_price = forms.IntegerField(max_value=10000000)
    count = forms.IntegerField(max_value=100)

stock/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import searchForm, requestForm
from .models import Stock, StockManager, InvestUser
from django.db.models import Q

import random

def main(request):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    stocks = Stock.objects.all()
    stock_business = []

    for stock in stocks:
        if stock.business not in stock_business:
            stock_business.append(stock.business)

    business = request.GET.get('business')
    if(business!=None):
        stocks = Stock.objects.filter(business=business)
    else:
        business='건설업'
        stocks = Stock.objects.filter(business=business)
    context = {
        'business':business,
        'stock_business': stock_business,
        'searchForm':searchForm(),
        'stocks':stocks
    }
    return render(request, 'stock/main.html', context)

def random_stock(request):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    stocks = Stock.objects.all()
    rand_num = random.randint(0, stocks.count())
    stock = stocks[rand_num]
    return HttpResponseRedirect(reverse('stock:stock_detail', args=(stock.code, )))

def stock_detail(request, code):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    stock = Stock.objects.get(code=code)
    stock.stock_reset()
    context = {
        'stock': stock,
        'searchForm':searchForm()
    }
    return render(request, 'stock/stock_detail.html', context)

def buy_sell(request, code):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    stock = Stock.objects.get(code=code)
    stock.stock_reset()
    buy_prices, sell_price = stock.asking_price()
    own_count, request_buy,request_sell=stock.about_stock(request.user)
    context = {
        'stock':stock,
        'buy_prices': buy_prices,
        'sell_prices': sell_price,
        'own_count' : own_count,
        'request_buy': request_buy,
        'request_sell': request_sell,
        'searchForm':searchForm(),
    }
    return render(request, 'stock/stock_buy_sell.html', context)


def stock_search(request):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))

    if request.method == 'POST':
        """
        if search_form.is_valid(): 오류 발생
        """
        title = request.POST.get('title', '')
        stocks = Stock.objects.filter(title__contains=title)
        if stocks.count() == 1:
            return HttpResponseRedirect(reverse('stock:stock_detail', args=(stocks[0].code,)))
        else:
            return render(request, 'stock/stock_search.html', {'stocks': stocks,'searchForm':searchForm()})
    return HttpResponseRedirect(reverse('stock:main'))


def stock_request(request, code):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))

    if request.method == "POST":
        request_flag = int(request.POST.get('request_flag', ''))
        request_price = int(request.POST.get('request_price', ''))
        count = int(request.POST.get('count', ''))
        print(request_flag, request_price, count)
        if request_flag == 0:
            print("매도")
            new_stock = StockManager.objects.create(user=request.user, stock=Stock.objects.get(code=code))
            result = new_stock.sell(request_price, count)
            if result != 1:
                messages.add_message(request, messages.INFO, result)
                return redirect('stock:stock_detail', code=code)
            new_stock.conclusion()
        elif request_flag == 1:
            print("매수")
            new_stock = StockManager.objects.create(user=request.user, stock=Stock.objects.get(code=code))
            result = new_stock.buy(request_price, count)
            if result != 1:
                messages.add_message(request, messages.INFO, result)
                return redirect('stock:stock_detail', code=code)
            new_stock.conclusion()
    return HttpResponseRedirect(reverse('stock:Balances'))

def balances(request):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    if request.method == 'POST':
        if request.POST['request_cancel'] == '취소':
            stock = StockManager.objects.get(pk=int(request.POST.get('stock')))
            stock.cancel()
    own_stock = request.user.own_stock()
    log_stock = request.user.log_stock()
    stock_balances = StockManager.objects.filter(user=request.user).filter(Q(request_flag=0, flag=1) | Q(request_flag=1) | Q(request_cancel=1)).order_by('-create_time')
    context = {
        'own_stocks':own_stock,
        'log_stocks':log_stock,
        'searchForm':searchForm(),
        'stock_balances':stock_balances
    }
    return render(request, 'stock/Balances.html', context)

def ranking(request):
    if(not request.user.is_authenticated):
        return HttpResponseRedirect(reverse('home'))
    InvestUse = InvestUser.objects.all()
    users = []
    for user in InvestUse:
        user.total_money_reset()
    users = InvestUser.objects.all().order_by('-total_money')
    context =  {
        'users':users
    }
    return render(request, 'stock/ranking.html', context)

templates/stock/main.html
{% extends 'base.html' %}

{% block title %}Stock main{% endblock %}

{% block body %}
<div id="content" class="row-fluid" style="padding-left: 10%;padding-right:20px;">
<div class="span2 sidebar" style="
    /* margin-left: 63px; */
">
    <ul class="nav nav-tabs nav-stacked" style="background-color: #fff;">

      {% for stock in stock_business %}
          <li><a href="?business={{ stock }}">{{ stock }}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div class="span8 main" style="width: 50%;background-color: #fff;">
    <table class="table table-hover">
            <thead>
                <tr>
                    <th>종목</th>
                    <th>현재가</th>
                    <th>등락률</th>
                </tr>
            </thead>
            <tbody>
              {% for stock in stocks%}
              <tr>
                <td><a href="{% url 'stock:stock_detail' stock.code %}">{{stock.title}}</a></td>
                <td>{{ stock.price }}</td>
                {% if stock.change > 0 %}
                <td><span class='red'>+{{ stock.change }}%</span></td>
                {% elif stock.change < 0 %}
                <td><span class='blue'>{{ stock.change }}%</span></td>
                {% else %}
                <td><span>{{ stock.change }}%</span></td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
        </table>
  </div>
</div>
{% endblock %}

templates/stock/ranking.html
{% extends 'base2.html' %}

{% block title %}Stock main{% endblock %}

{% block body %}
{% load static %}
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar" style="padding-top: 0px;background-color: #3338D3;">
    <ul class="nav nav-sidebar">
        <li>
            <a href="{% url 'stock:random_stock' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stockicon.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">종목</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock_analysis:first' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stock2.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">주식분석</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock:Balances' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'leftmoney.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">잔고</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'stock:ranking' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'rank.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">순위</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'contest:contest' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'competition.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">대회공지</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>

        <li id="myBtn">
            <a href="#" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'tutorial.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">튜토리얼</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'term:term' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static  'dic.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">용어사전</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
    </ul>
    <img src="{% static 'sidebarBg.png' %}"style="position: absolute;height: 150px;right: 0;bottom: 0;">
</div>
    </div>
</div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;">
            <div class="row">
                <div class="col-sm-8 blog-main" style="margin-bottom: 30px;">
                  <div class="blog-post" style="background-color: #fff;">
                      <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">순위</span></h4>
                        <table class="table table-hover">
                          <thead>
                              <tr>
                                  <th>순위</th>
                                  <th>아이디</th>
                                  <th>닉네임</th>
                                  <th>통장잔액</th>
                                  <th>보유 주식 가치</th>
                                  <th>총자산</th>
                              </tr>
                          </thead>
                          <tbody>
                            {% for user in users %}
                            <tr>
                              <td>{{ forloop.counter }}</td> <td>{{ user.username }}</td> <td>{{ user.nickname }}</td>
                              <td>{{ user.money }}</td> <td>{{ user.take_price }}</td> <td>{{ user.total_money }}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                          </table>
                  </div>
              </div>
       </div>
    </div>
</div>
{% endblock %}

templates/stock/stock_detail.html
{% extends 'base2.html' %}

{% block title %}Stock Detail{% endblock %}

{% block body %}
{% load static %}
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar" style="padding-top: 0px;background-color: #3338D3;">
    <ul class="nav nav-sidebar">
        <li class="active">
            <a href="{% url 'stock:random_stock' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stockicon.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">종목</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock_analysis:first' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stock2.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">주식분석</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock:Balances' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'leftmoney.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">잔고</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'stock:ranking' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'rank.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">순위</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'contest:contest' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'competition.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">대회공지</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>

        <li id="myBtn">
            <a href="#" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'tutorial.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">튜토리얼</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
        <li>
            <a href="{% url 'term:term' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                <table style="height: 100%;">
                    <tbody>
                        <tr>
                            <td style="width: 40px;background-color: #2E31BB;"><img src="{% static  'dic.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                            <td style="padding-left: 10px;">용어사전</td>
                        </tr>
                    </tbody>
                </table>
            </a>
        </li>
    </ul>
    <img src="{% static 'sidebarBg.png' %}"style="position: absolute;height: 150px;right: 0;bottom: 0;">
</div>
    </div>
</div>
<<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;">
                <div class="row">
                    <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
                      <div>
                          <nav style="font-size: 20px;margin-bottom: 25px;  margin-left:37px;">
                              <b><a href="{% url 'stock:stock_detail' stock.code %}" style="color: #000;">현재가</a> | <a href="{% url 'stock:buy_sell' stock.code %}" style="color: #000;">매도/매수</a>
                              <br>
                              </b>
                          </nav>
                      </div>
                        <div class="blog-post" style="background-color: #fff;">
                            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;margin: 0;">
                                <div class="row">
                                    <div class="col-sm-8 blog-main" style="margin-bottom: 30px;">
                                      <div class="blog-post" style="background-color: #fff; width:350px;">
                                          <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">{{ stock.title }}</span></h4>
                                          {% if stock.change > 0 %}
                                            <span style="margin-left:12px; font-size:28px;color: #d40400; " >{{ stock.price }}</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:20px;color: #d40400;">+{{ stock.change }}%</span> <br>
                                          {% elif stock.change < 0 %}
                                            <span style="margin-left:12px;font-size:28px;color: #005dde; " >{{ stock.price }}</span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:20px;color: #005dde;">{{ stock.change }}%</span> <br>
                                          {% else %}
                                          <span style="margin-left:12px;font-size:28px;" >{{ stock.price }}</span> &nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:20px;">+{{ stock.change }}%</span> <br>
                                          {% endif %}
                                          <div style="margin-left: 10px;">
                                              <div id="img_change" class="btn-group" data-toggle="buttons" style="width: 300px;">
                                                  <span class="btn btn-primary" onclick="check_only(this)">1일</span>
                                                  <span class="btn btn-primary" onclick="check_only(this)">1개월</span>
                                                  <span class="btn btn-primary" onclick="check_only(this)">3개월</span>
                                                  <span class="btn btn-primary" onclick="check_only(this)">1년</span>
                                            </div>
                                            <br><br>
                                            <div id="graph_img"> <img src="{{ stock.today_graph }}" alt=""><br><br></div> </div>
                                      </div>
                                    </div>
                                </div>
<div class="row">
  <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
      <div class="blog-post" style="background-color: #fff;">
          <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">가격정보</span></h4>
          <table class="table table-hover">
             <thead>
                <tr><th></th><th></th><th></th><th></th></tr>
             </thead>
              <tr>
                <td>전일</td>
                <td>{{ stock.yesterday_price }}</td>
                    <td>시가</td>
                    <td>{{ stock.today_start_price }}</td>
              </tr>
              <tr>
                 <td>고가</td>
                  <td>{{ stock.high_price }}</td>
                <td>저가</td>
              <td>{{ stock.low_price }}</td>
          </tr>

            <tr>
              <td>상한가</td>
              <td>{{ stock.max_price }}</td>
              <td>하한가</td>
              <td>{{ stock.min_price }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
                        <!-- /.blog-post -->
                    </div>
                    <!-- /.blog-main -->
                    <!-- /.blog-sidebar -->
                </div>
            </div>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>
    <script>
    document.getElementsByName("chkbox")[0].checked = true;
    function changeValue(val){
      if(val==0){
        {% for sell in sell_prices %}
          document.getElementById("price").getElementsByTagName("option")[{{forloop.counter0}}].setAttribute("value", {{ sell }})
          document.getElementById("price").getElementsByTagName("option")[{{forloop.counter0}}].innerHTML={{ sell }}
          {% endfor %}
        }
        else{
          {% for buy in buy_prices %}
            document.getElementById("price").getElementsByTagName("option")[{{forloop.counter0}}].setAttribute("value", {{ buy }})
            document.getElementById("price").getElementsByTagName("option")[{{forloop.counter0}}].innerHTML={{ buy }}
          {% endfor %}
        }
      }
      function check_only(chk){
        var obj = document.getElementById("img_change").getElementsByTagName("span");
        for(var i=0; i<obj.length; ++i){
          if (obj[i] == chk){
            console.log(i);
            break;
          }
        }
        console.log(i);
        if(i==0){
          document.getElementById("graph_img").getElementsByTagName("img")[0].setAttribute("src", '{{ stock.today_graph }}')
        }
        else if(i==1){
            document.getElementById("graph_img").getElementsByTagName("img")[0].setAttribute("src", '{{ stock.month_graph }}')
        }
        else if(i==2){
          document.getElementById("graph_img").getElementsByTagName("img")[0].setAttribute("src", '{{ stock.three_month_graph }}')
        }
        else{
          document.getElementById("graph_img").getElementsByTagName("img")[0].setAttribute("src", '{{ stock.year_graph }}')
        }
  }
    </script>
{% endblock %}
<!--
전일 : {{ stock.yesterday_price }} 고가 : {{ stock.high_price }} <br>
시가 : {{ stock.today_start_price }} 저가 : {{ stock.low_price }} <br>
상한가 : {{ stock.max_price }} 하한가 : {{ stock.min_price }}
<br><br>
<a href="#">매도/매수</a> <a href="#">차트</a> <a href="#">기업 정보</a>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<br><br>
<table>
    <tr>
        <th>매도 호가</th>
    </tr>
    {% for sell in sell_prices %}
        <tr>
            <td>{{ sell }}</td>
        </tr>
    {% endfor %}
    <tr>
        <th>매수 호가</th>
    </tr>
    {% for buy in buy_prices %}
        <tr>
            <td>{{ buy }}</td>
        </tr>
    {% endfor %}
</table>
{{ request.user.nickname }}님의 소지 금액 : {{ request.user.money }} <br>
보유 주식 : {{ own_count }}개 <br>
매수 신청 : {{ request_buy }}개 <br>
매도 신청 : {{ request_sell }}개 <br>
<form action="{% url 'stock:request' stock.code %}" method="POST">
    {% csrf_token %}
    <select name="request_flag" id="stock" onchange="changeValue(this.value)">
        <option value="0">매도
        <option value="1">매수
    </select>
    <select id="price" name="request_price">
        {% for price in sell_prices %}
            <option value="{{price}}">{{price}}
        {% endfor %}
    </select>
    <input type="number" name="count" value="1" min="1" max="100" step="1">
    <input type="submit" name="name" value="submit">
</form>
-->