contest/urls.py
from django.conf.urls import url

from .views import contest

urlpatterns=  [
    url(r'^$', contest, name='contest'),
]

invest_house/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import Home, Sign_up, mypage,exit, setting_login

from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'accounts/lgoun/$', setting_login, name='login'),
    url(r'^accounts/logout/$', logout, {'next_page': '/home'}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),

    url(r'^$', Home),
    url(r'^home/$', Home, name='home'),
    url(r'^sign-up/$', Sign_up.as_view(), name='sign-up'),
    url(r'^mypage/$', mypage, name='mypage'),
    url(r'^exit-exit_exit/$', exit, name='exit'),

    url(r'^stock/', include('stock.urls', namespace='stock')),

    url(r'^stock_analsis/', include('stock_analysis.urls', namespace="stock_analysis")),

    url(r'^tutorial/', include('tutorial.urls', namespace="tutorial")),

    url(r'^contest/', include('contest.urls', namespace='contest')),

    url(r'^term/', include('term.urls', namespace='term')),
]

stock/urls.py
from django.conf.urls import url

from .views import main, stock_detail, stock_search, balances, stock_request, ranking, random_stock, buy_sell


urlpatterns = [
    url(r'^main/$', main, name='main'),
    url(r'random_stock/$', random_stock, name='random_stock'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/$', stock_detail, name='stock_detail'),
    url(r'^detail/(?P<code>[A-Za-z-0-9]+)/buy_sell/$', buy_sell, name='buy_sell'),
    url(r'^search/$', stock_search, name='search'),
    url(r'^request/(?P<code>[A-Za-z-0-9]+)/$', stock_request, name="request"),
    url(r'^balances/$', balances, name="Balances"),
    url(r'^ranking/$', ranking, name="ranking"),
]

stock_analysis/urls.py
from django.conf.urls import url

from .views import trade, increase, decrease

urlpatterns = [
    url(r'^$', trade, name='first'),
    url(r'^trade/$', trade, name="trade"),
    url(r'^increase/$', increase, name='increase'),
    url(r'^decrease/$', decrease, name='decrease'),
]

term/urls.py
from django.conf.urls import url

from .views import term

urlpatterns = [
    url(r'^$', term, name='term')
]

stock_analysis/views.py
from django.shortcuts import render

from stock.models import Stock
from stock.forms import searchForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def trade(request):
    trade_list = Stock.objects.all().order_by('-deal')
    paginator = Paginator(trade_list, 100)

    page = request.GET.get('page', '')

    try:
        add = (int(page)-1) * 100
    except:
        pass

    try:
        trade_page = paginator.page(page)
    except PageNotAnInteger:
        add = 0
        trade_page = paginator.page(1)
    except EmptyPage:
        add =  (paginator.num_pages-1) * 100
        trade_page = paginator.page(paginator.num_pages)
    context = {
        'trade_page': trade_page,
        'pagination_range': paginator.page_range,
        'searchForm': searchForm(),
        'add':add
    }
    return render(request, 'stock_analysis/trade.html', context)


def increase(request):
    increase_list = Stock.objects.filter(change__gt=0).order_by('-change')
    paginator = Paginator(increase_list, 100)
    page = request.GET.get('page', '')

    try:
        add = (int(page)-1) * 100
    except:
        pass

    try:
        increase_page = paginator.page(page)
    except PageNotAnInteger:
        add = 0
        increase_page = paginator.page(1)
    except EmptyPage:
        add = (paginator.num_pages-1) * 100
        increase_page = paginator.page(paginator.num_pages)
    context = {
        'trade_page': increase_page,
        'pagination_range': paginator.page_range,
        'searchForm': searchForm(),
        'add':add
    }
    return render(request, 'stock_analysis/increase.html', context)

def decrease(request):
    decrease_list = Stock.objects.filter(change__lt=0).order_by('change')
    paginator = Paginator(decrease_list, 100)
    page = request.GET.get('page', '')

    try:
        add = (int(page)-1) * 100
    except:
        pass

    try:
        decrease_page = paginator.page(page)
    except PageNotAnInteger:
        add = 0
        decrease_page = paginator.page(1)
    except EmptyPage:
        add =  (paginator.num_pages-1) * 100
        decrease_page = paginator.page(paginator.num_pages)
    context = {
        'trade_page': decrease_page,
        'pagination_range': paginator.page_range,
        'searchForm': searchForm(),
        'add':add,
    }
    return render(request, 'stock_analysis/decrease.html', context)

templates/stock_analysis/decrease.html
{% extends 'base2.html' %}
  {% load static %}

  {% block title %}Stock Trade{% endblock %}

  {% block stylesheet %}
      <link href="{% static 'css/trade.css' %}" rel="stylesheet">
  {% endblock %}

  {% block body %}
  <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar" style="padding-top: 0px;background-color: #3338D3;">
          <ul class="nav nav-sidebar">
              <li>
                  <a href="{% url 'stock:random_stock' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stockicon.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">종목</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li class="active">
                  <a href="{% url 'stock_analysis:first' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stock2.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">주식분석</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'stock:Balances' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'leftmoney.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">잔고</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'stock:ranking' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'rank.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">순위</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'contest:contest' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'competition.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">대회공지</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>

              <li id="myBtn">
                  <a href="#" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'tutorial.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">튜토리얼</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'term:term' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static  'dic.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">용어사전</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
          </ul>
          <img src="{% static 'sidebarBg.png' %}"style="position: absolute;height: 150px;right: 0;bottom: 0;">
      </div>
          </div>
      </div>
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="
      background-color: #F8F0ED;">
                  <div class="row">
                      <div class="col-sm-8 blog-main" style="
      width: 100%;
      margin-bottom: 30px;
  ">
                          <div class="blog-post" style="
      background-color: #fff;">
                              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;margin: 0;">
                                <div>
                                    <nav style="font-size: 20px;margin-bottom: 25px;">
                                        <b><a href="{% url 'stock_analysis:trade' %}" style="color: #000;">현재가</a> | <a href="{% url 'stock_analysis:increase' %}" style="color: #000;">상승</a> | <a href="{% url 'stock_analysis:decrease' %}" style="color: #000; ">하락</a>
                                        <br>
                                        </b>
                                    </nav>
                                </div>
                                  <div class="row">
                                      <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
                                          <div class="blog-post" style="background-color: #fff;">
                                              <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">하락</span></h4>
                                              <table class="table table-hover">
    <thead>
      <tr>
        <th>순위</th>
        <th>종목</th>
        <th>현재가</th>
        <th>등락률</th>
        <th>거래량</th>
      </tr>
    </thead>
    <tbody>
      {% for stock in trade_page.object_list %}
      <tr>
        <th scope="row">{{ forloop.counter|add:add }}</th>
        <td><a href="{% url 'stock:stock_detail' stock.code %}">{{ stock.title }}</a></td>
        <td>{{ stock.price }}</td>
        {% if stock.change > 0 %}
          <td class="red" >+{{ stock.change }}%</td>
        {% elif stock.change < 0 %}
          <td class="blue" >{{ stock.change }}%</td>
        {% else %}
          <td>{{ stock.change }}</td>
        {% endif %}
        <td>{{ stock.deal }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


                                          </div>
  <nav aria-label="Page navigation">
    {% if trade_page.has_other_pages %}
        <ul class="pagination">
            {% if trade_page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ trade_page.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item"><a class="disabled page-link"><span>&laquo;</span></a></li>
            {% endif %}
            {% for page in trade_page.paginator.page_range %}
                {% if trade_page.number == page %}
                    <li class="page-item"><a class="active page-link"><span>{{ page }}</span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            {% if trade_page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ trade_page.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link disabled"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
        </div>
                                  </div>
                              </div>
                          </div>
                          <!-- /.blog-post -->
                      </div>
                      <!-- /.blog-main -->
                      <!-- /.blog-sidebar -->
                  </div>
              </div>
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;">
                  <div class="row">
                      <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
                          <div class="blog-post" style="background-color: #fff;">
                              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;margin: 0;"> </div>
                          </div>
                          <!-- /.blog-post -->
                      </div>
                      <!-- /.blog-main -->
                      <!-- /.blog-sidebar -->
                  </div>
              </div>
          </div>
      </div>
  {% endblock %}

<!--
{% for stock in decrease_page.object_list %}
  {{ forloop.counter }} {{ stock.title }} {{ stock.change }}<br>
{% endfor %}
{% if decrease_page.has_previous %}
    <a href="?page={{ decrease_page.previous_page_number }}">&laquo;</a>
{% else %}
    <a class="disabled"><span>&laquo;</span></a>
{% endif %}
{% for page in decrease_page.paginator.page_range %}
    {% if decrease_page.number == page %}
        <a class="active"><span>{{ page }} (current)</span></a>
    {% else %}
        <a href="?page={{ page }}">{{ page }}</a>
    {% endif %}
{% endfor %}
{% if increase.has_next %}
    <a href="?page={{ decrease_page.next_page_number }}">&raquo;</a>
{% else %}
    <a class="disabled"><span>&raquo;</span></a>
{% endif %}
-->

templates/stock_analysis/increase.html
{% extends 'base2.html' %}
  {% load static %}

  {% block title %}Stock Trade{% endblock %}

  {% block stylesheet %}
      <link href="{% static 'css/trade.css' %}" rel="stylesheet">
  {% endblock %}

  {% block body %}
  <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar" style="padding-top: 0px;background-color: #3338D3;">
          <ul class="nav nav-sidebar">
              <li>
                  <a href="{% url 'stock:random_stock' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stockicon.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">종목</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li class="active">
                  <a href="{% url 'stock_analysis:first' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'stock2.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">주식분석</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'stock:Balances' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'leftmoney.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">잔고</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'stock:ranking' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'rank.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">순위</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'contest:contest' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'competition.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">대회공지</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>

              <li id="myBtn">
                  <a href="#" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static 'tutorial.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">튜토리얼</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
              <li>
                  <a href="{% url 'term:term' %}" style="border-bottom-style: solid;height: 40px;padding: 0;border-top-style: solid;border-color: rgba(255,255,255,0.3);border-width: 1px; height: 50px;color: #fff;">
                      <table style="height: 100%;">
                          <tbody>
                              <tr>
                                  <td style="width: 40px;background-color: #2E31BB;"><img src="{% static  'dic.png' %}" style="margin-left: 7px;width: 25px;height: 25px;"></td>
                                  <td style="padding-left: 10px;">용어사전</td>
                              </tr>
                          </tbody>
                      </table>
                  </a>
              </li>
          </ul>
          <img src="{% static 'sidebarBg.png' %}"style="position: absolute;height: 150px;right: 0;bottom: 0;">
      </div>
          </div>
      </div>
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="
      background-color: #F8F0ED;">
                  <div class="row">
                      <div class="col-sm-8 blog-main" style="
      width: 100%;
      margin-bottom: 30px;
  ">
                          <div class="blog-post" style="
      background-color: #fff;">
                              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;margin: 0;">
                                <div>
                                    <nav style="font-size: 20px;margin-bottom: 25px;">
                                        <b><a href="{% url 'stock_analysis:trade' %}" style="color: #000;">거래량</a> | <a href="{% url 'stock_analysis:increase' %}" style="color: #000;">상승</a> | <a href="{% url 'stock_analysis:decrease' %}" style="color: #000; ">하락</a>
                                        <br>
                                        </b>
                                    </nav>
                                </div>

                                  <div class="row">
                                      <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
                                          <div class="blog-post" style="background-color: #fff;">
                                              <h4 class="blog-post-title" style="background-color: #F8F0ED;"><span style="padding-right: 15px;padding-left: 15px;background-color: #fff;padding-top: 10px;padding-bottom: 10px;">상승</span></h4>
                                              <table class="table table-hover">
    <thead>
      <tr>
        <th>순위</th>
        <th>종목</th>
        <th>현재가</th>
        <th>등락률</th>
        <th>거래량</th>
      </tr>
    </thead>
    <tbody>
      {% for stock in trade_page.object_list %}
      <tr>
        <th scope="row">{{ forloop.counter|add:add }}</th>
        <td><a href="{% url 'stock:stock_detail' stock.code %}">{{ stock.title }}</a></td>
        <td>{{ stock.price }}</td>
        {% if stock.change > 0 %}
          <td class="red" >+{{ stock.change }}%</td>
        {% elif stock.change < 0 %}
          <td class="blue" >{{ stock.change }}%</td>
        {% else %}
          <td>{{ stock.change }}</td>
        {% endif %}
        <td>{{ stock.deal }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


                                          </div>
  <nav aria-label="Page navigation">
    {% if trade_page.has_other_pages %}
        <ul class="pagination">
            {% if trade_page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ trade_page.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item"><a class="disabled page-link"><span>&laquo;</span></a></li>
            {% endif %}
            {% for page in trade_page.paginator.page_range %}
                {% if trade_page.number == page %}
                    <li class="page-item"><a class="active page-link"><span>{{ page }}</span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            {% if trade_page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ trade_page.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link disabled"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
        </div>
                                  </div>
                              </div>
                          </div>
                          <!-- /.blog-post -->
                      </div>
                      <!-- /.blog-main -->
                      <!-- /.blog-sidebar -->
                  </div>
              </div>
              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;">
                  <div class="row">
                      <div class="col-sm-8 blog-main" style="width: 100%;margin-bottom: 30px;">
                          <div class="blog-post" style="background-color: #fff;">
                              <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="background-color: #F8F0ED;margin: 0;"> </div>
                          </div>
                          <!-- /.blog-post -->
                      </div>
                      <!-- /.blog-main -->
                      <!-- /.blog-sidebar -->
                  </div>
              </div>
          </div>
      </div>
  {% endblock %}

<!--
{% for stock in increase_page.object_list %}
  {{ forloop.counter }} {{ stock.title }} {{ stock.change }}<br>
{% endfor %}
{% if increase_page.has_other_pages %}
    <div class="pagination">
        {% if increase_page.has_previous %}
            <a href="?page={{ increase_page.previous_page_number }}">&laquo;</a>
        {% else %}
            <a class="disabled"><span>&laquo;</span></a>
        {% endif %}
        {% for page in increase_page.paginator.page_range %}
            {% if increase_page.number == page %}
                <a class="active"><span>{{ page }} (current)</span></a>
            {% else %}
                <a href="?page={{ page }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
        {% if increase.has_next %}
            <a href="?page={{ increase_page.next_page_number }}">&raquo;</a>
        {% else %}
            <a class="disabled"><span>&raquo;</span></a>
        {% endif %}
    </div>
{% endif %}
-->